#ifndef FILE_TYPE_H
#define FILE_TYPE_H

#include "util/defs.h"

#include <assert.h>
#include <stdlib.h>

typedef enum
{
  FILE_TYPE_RELOCATABLE_OBJECT = 0x1,
  FILE_TYPE_DEMAND_PAGED_EXECUTABLE = 0x2,
  FILE_TYPE_FIXED_VM_SHARED_LIBRARY = 0x3,
  FILE_TYPE_CORE = 0x4,
  FILE_TYPE_PRELOADED_EXECUTABLE = 0x5,
  FILE_TYPE_DYNAMICALLY_BOUND_SHARED_LIBRARY = 0x6,
  FILE_TYPE_DYNAMIC_LINK_EDITOR = 0x7,
  FILE_TYPE_DYNAMICALLY_BOUND_BUNDLE = 0x8,
  FILE_TYPE_SHARED_LIBRARY_STUB = 0x9,
  FILE_TYPE_COMPANION_DEBUG_ONLY = 0xA,
  FILE_TYPE_X86_64_KEXTS = 0xB,
  FILE_TYPE_LINKEDIT_SHARING = 0xC,
  FILE_TYPE_LAST = FILE_TYPE_LINKEDIT_SHARING + 1,
} file_type_t;
static_assert(sizeof(file_type_t) == sizeof(int32_t));

#endif /* FILE_TYPE_H */